version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server:/usr/src/app
    environment:
      NODE_ENV: development
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_PORT: 27017
      MONGO_HOST: mongo
    depends_on:
      - mongo

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./apps/client:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - server

volumes:
  mongo_data:
